#!/bin/bash

##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=mixtralEXP1       #Set the job name to "JobExample3"
#SBATCH --time=6:00:00            #Set the wall clock limit to 1 Day and 12hr
#SBATCH --nodes=1                    #Request 1 node
#SBATCH --cpus-per-task=24          #Request 2 tasks/cores per node
#SBATCH --mem=32768M                  #Request 4096MB (4GB) per node 
#SBATCH --output=mixtralEXP1.%j      #Send stdout/err to "Example3Out.[jobID]"



##OPTIONAL JOB SPECIFICATIONS
##SBATCH --account=123456             #Set billing account to 123456
##SBATCH --mail-type=ALL              #Send email on all job events
#SBATCH --mail-user=siweicui@tamu.edu    #Send all emails to email_address

#First Executable Line

cd $SCRATCH
module add GCC/10.3.0  OpenMPI/4.1.1
# module add PyTorch/1.10.0
# module add Anaconda3/2022.05
# module add CMake/3.20.1
# module add CUDA/12.2

module load WebProxy
/bin/bash
source activate llm
# https://github.com/hendrycks/test
cd /scratch/user/siweicui/benchmark/test

python evaluate_mixtral_cpp.py  --nexpert 1

