#!/bin/bash

##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=NeuralSpeed       #Set the job name to "JobExample3"
#SBATCH --time=3:00:00            #Set the wall clock limit to 1 Day and 12hr
#SBATCH --nodes=1                   #Request 1 node
#SBATCH --cpus-per-task=32          #Request 2 tasks/cores per node
#SBATCH --mem=305536M                  #Request 4096MB (4GB) per node 
#SBATCH --output=NeuralSpeed.%j      #Send stdout/err to "Example3Out.[jobID]"
#SBATCH --mail-user=siweicui@tamu.edu    #Send all emails to email_address



#First Executable Line

cd $SCRATCH
module add GCC/10.3.0  
# module add PyTorch/1.10.0
# module add Anaconda3/2022.05
# module add CMake/3.20.1
# module add CUDA/12.2

module load WebProxy
/bin/bash
source activate llm
cd /scratch/user/siweicui/mix_precision
jupyter nbconvert --execute --to notebook ./neural_speed.ipynb


